In [1]:
%autosave 20

import pandas as pd
import numpy as np

# print all the outputs in a cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Autosaving every 20 seconds

In [2]:
df = pd.read_excel('final_database.xlsx', index_col=0)

In [3]:
df.info( )

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236340 entries, 0 to 236339
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Search              236340 non-null  int64
 1   Search term         236340 non-null  object
 2   Region              236340 non-null  object
 3   State               236340 non-null  object
 4   Year                236340 non-null  int64
 5   Month               236340 non-null  int64
 6   County              236340 non-null  object
 7   CountyInsideRegion  236340 non-null  object
 8   Population Density  236340 non-null  float64
 9   Population          236340 non-null  int64
 10  SNAP_Applications   236340 non-null  int64
 11  Number of Workers   236340 non-null  int64
 12  # of disaster       236340 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 25.2+ MB

In [4]:
df.head(10)

,Search,Search term,Region,State,Year,Month,County,CountyInsideRegion,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster
0,24,calfresh,Los Angeles CA,California,2019,1,Inyo,Los Angeles,1.8,18439,84,0,0
1,24,calfresh,Los Angeles CA,California,2019,1,Kern,Los Angeles,105.1,857730,6163,134,0
2,24,calfresh,Los Angeles CA,California,2019,1,Orange,Los Angeles,3255.4,3086331,8637,200,0
3,24,calfresh,Los Angeles CA,California,2019,1,San Diego,Los Angeles,703.4,3183143,12905,140,0
4,24,calfresh,Los Angeles CA,California,2019,1,Santa Barbara,Los Angeles,113.9,431555,2509,0,0
5,24,calfresh,Los Angeles CA,California,2019,1,Tulare,Los Angeles,93.2,451108,2231,63,0
6,24,calfresh,Los Angeles CA,California,2019,1,Ventura,Los Angeles,378.5,835790,2956,0,0
7,34,calfresh,Los Angeles CA,California,2019,1,Inyo,Los Angeles,1.8,18439,84,0,0
8,34,calfresh,Los Angeles CA,California,2019,1,Kern,Los Angeles,105.1,857730,6163,134,0
9,34,calfresh,Los Angeles CA,California,2019,1,Orange,Los Angeles,3255.4,3086331,8637,200,0

In [5]:
# del some useless cols
cols = ['Region', 'CountyInsideRegion']

df.drop(columns=cols, inplace=True)

In [6]:
df.head(20)

,Search,Search term,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster
0,24,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
1,24,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
2,24,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
3,24,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
4,24,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0
5,24,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0
6,24,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0
7,34,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
8,34,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
9,34,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
10,34,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
11,34,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0
12,34,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0
13,34,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0
14,26,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
15,26,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
16,26,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
17,26,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
18,26,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0
19,26,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0

### Build variable for the model/function

In [7]:
df1 = df.copy()

In [8]:
df1.head()

,Search,Search term,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster
0,24,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
1,24,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
2,24,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
3,24,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
4,24,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0

### Create date_time, last_date_time, last_snap, last_number of workder, last # of disater for the df1

In [9]:



# create date_time
from datetime import datetime
df1['date_time'] = 0

for i in range(len(df1)):
    cur_year = str(df1.iloc[i, 3]) # 3 is the index of year
    cur_mon = str(df1.iloc[i, 4]) # 4 is the index of year
    cur_date_string = cur_year + ' ' + cur_mon
    cur_datetime_string = pd.to_datetime(cur_date_string)
    df1.iloc[i, -1] = cur_datetime_string # -1 is the index of date_time in this step
    

# create last_date_time
df1['last_date_time'] = 0

for i in range(len(df1)):
    dtDate = df1.iloc[i,-2] # -2 is the index of date_time in this step
    df1.iloc[i,-1] = dtDate - pd.DateOffset(months=1)

In [10]:
df1.head()

,Search,Search term,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster,date_time,last_date_time
0,24,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00
1,24,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0,2019-01-01 00:00:00,2018-12-01 00:00:00
2,24,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0,2019-01-01 00:00:00,2018-12-01 00:00:00
3,24,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0,2019-01-01 00:00:00,2018-12-01 00:00:00
4,24,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00

### Find last_snap, last_workder, last_disater by the key [last_date_time, County and State]

In [16]:
df1['last_snap'] = None
df1['last_worker'] = None
df1['last_disaster'] = None

for i in range(len(df1)):
    state = df1.iloc[i, 2]
    county = df1.iloc[i, 5]
    last_date_time = df1.last_date_time[i]
    
    filtet_table = df1.loc[(df1.date_time == last_date_time) & (df1.State == state) & (df1.County == county)]
    
    
    if len(filtet_table) != 0:
        df1.iloc[i, -1] = filtet_table['# of disaster'].values[0]
        df1.iloc[i, -2] = filtet_table['Number of Workers'].values[0]
        df1.iloc[i, -3] = filtet_table.SNAP_Applications.values[0]

In [17]:
df1.head(100)

,Search,Search term,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster,date_time,last_date_time,last_snap,last_worker,last_disaster
0,24,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
1,24,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
2,24,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
3,24,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
4,24,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
5,24,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
6,24,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
7,34,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
8,34,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
9,34,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
10,34,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
11,34,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
12,34,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
13,34,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
14,26,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
15,26,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
16,26,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
17,26,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
18,26,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
19,26,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
20,26,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
21,26,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
22,26,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
23,26,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
24,26,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
25,26,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
26,26,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
27,26,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0,2019-01-01 00:00:00,2018-12-01 00:00:00,None,None,None
28,28,calfresh,California,2019,2,Inyo,1.8,18439,38,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,84,0,0
29,28,calfresh,California,2019,2,Kern,105.1,857730,4841,175,0,2019-02-01 00:00:00,2019-01-01 00:00:00,6163,134,0
30,28,calfresh,California,2019,2,Orange,3255.4,3086331,6872,350,0,2019-02-01 00:00:00,2019-01-01 00:00:00,8637,200,0
31,28,calfresh,California,2019,2,San Diego,703.4,3183143,10538,268,0,2019-02-01 00:00:00,2019-01-01 00:00:00,12905,140,0
32,28,calfresh,California,2019,2,Santa Barbara,113.9,431555,1828,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2509,0,0
33,28,calfresh,California,2019,2,Tulare,93.2,451108,1809,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2231,63,0
34,28,calfresh,California,2019,2,Ventura,378.5,835790,2436,246,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2956,0,0
35,20,calfresh,California,2019,2,Inyo,1.8,18439,38,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,84,0,0
36,20,calfresh,California,2019,2,Kern,105.1,857730,4841,175,0,2019-02-01 00:00:00,2019-01-01 00:00:00,6163,134,0
37,20,calfresh,California,2019,2,Orange,3255.4,3086331,6872,350,0,2019-02-01 00:00:00,2019-01-01 00:00:00,8637,200,0
38,20,calfresh,California,2019,2,San Diego,703.4,3183143,10538,268,0,2019-02-01 00:00:00,2019-01-01 00:00:00,12905,140,0
39,20,calfresh,California,2019,2,Santa Barbara,113.9,431555,1828,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2509,0,0
40,20,calfresh,California,2019,2,Tulare,93.2,451108,1809,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2231,63,0
41,20,calfresh,California,2019,2,Ventura,378.5,835790,2436,246,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2956,0,0
42,21,calfresh,California,2019,2,Inyo,1.8,18439,38,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,84,0,0
43,21,calfresh,California,2019,2,Kern,105.1,857730,4841,175,0,2019-02-01 00:00:00,2019-01-01 00:00:00,6163,134,0
44,21,calfresh,California,2019,2,Orange,3255.4,3086331,6872,350,0,2019-02-01 00:00:00,2019-01-01 00:00:00,8637,200,0
45,21,calfresh,California,2019,2,San Diego,703.4,3183143,10538,268,0,2019-02-01 00:00:00,2019-01-01 00:00:00,12905,140,0
46,21,calfresh,California,2019,2,Santa Barbara,113.9,431555,1828,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2509,0,0
47,21,calfresh,California,2019,2,Tulare,93.2,451108,1809,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2231,63,0
48,21,calfresh,California,2019,2,Ventura,378.5,835790,2436,246,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2956,0,0
49,27,calfresh,California,2019,2,Inyo,1.8,18439,38,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,84,0,0
50,27,calfresh,California,2019,2,Kern,105.1,857730,4841,175,0,2019-02-01 00:00:00,2019-01-01 00:00:00,6163,134,0
51,27,calfresh,California,2019,2,Orange,3255.4,3086331,6872,350,0,2019-02-01 00:00:00,2019-01-01 00:00:00,8637,200,0
52,27,calfresh,California,2019,2,San Diego,703.4,3183143,10538,268,0,2019-02-01 00:00:00,2019-01-01 00:00:00,12905,140,0
53,27,calfresh,California,2019,2,Santa Barbara,113.9,431555,1828,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2509,0,0
54,27,calfresh,California,2019,2,Tulare,93.2,451108,1809,0,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2231,63,0
55,27,calfresh,California,2019,2,Ventura,378.5,835790,2436,246,0,2019-02-01 00:00:00,2019-01-01 00:00:00,2956,0,0
56,20,calfresh,California,2019,3,Inyo,1.8,18439,59,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,38,0,0
57,20,calfresh,California,2019,3,Kern,105.1,857730,5118,542,0,2019-03-01 00:00:00,2019-02-01 00:00:00,4841,175,0
58,20,calfresh,California,2019,3,Orange,3255.4,3086331,7611,543,0,2019-03-01 00:00:00,2019-02-01 00:00:00,6872,350,0
59,20,calfresh,California,2019,3,San Diego,703.4,3183143,10698,383,0,2019-03-01 00:00:00,2019-02-01 00:00:00,10538,268,0
60,20,calfresh,California,2019,3,Santa Barbara,113.9,431555,1707,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1828,0,0
61,20,calfresh,California,2019,3,Tulare,93.2,451108,2189,79,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1809,0,0
62,20,calfresh,California,2019,3,Ventura,378.5,835790,2730,174,0,2019-03-01 00:00:00,2019-02-01 00:00:00,2436,246,0
63,20,calfresh,California,2019,3,Inyo,1.8,18439,59,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,38,0,0
64,20,calfresh,California,2019,3,Kern,105.1,857730,5118,542,0,2019-03-01 00:00:00,2019-02-01 00:00:00,4841,175,0
65,20,calfresh,California,2019,3,Orange,3255.4,3086331,7611,543,0,2019-03-01 00:00:00,2019-02-01 00:00:00,6872,350,0
66,20,calfresh,California,2019,3,San Diego,703.4,3183143,10698,383,0,2019-03-01 00:00:00,2019-02-01 00:00:00,10538,268,0
67,20,calfresh,California,2019,3,Santa Barbara,113.9,431555,1707,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1828,0,0
68,20,calfresh,California,2019,3,Tulare,93.2,451108,2189,79,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1809,0,0
69,20,calfresh,California,2019,3,Ventura,378.5,835790,2730,174,0,2019-03-01 00:00:00,2019-02-01 00:00:00,2436,246,0
70,17,calfresh,California,2019,3,Inyo,1.8,18439,59,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,38,0,0
71,17,calfresh,California,2019,3,Kern,105.1,857730,5118,542,0,2019-03-01 00:00:00,2019-02-01 00:00:00,4841,175,0
72,17,calfresh,California,2019,3,Orange,3255.4,3086331,7611,543,0,2019-03-01 00:00:00,2019-02-01 00:00:00,6872,350,0
73,17,calfresh,California,2019,3,San Diego,703.4,3183143,10698,383,0,2019-03-01 00:00:00,2019-02-01 00:00:00,10538,268,0
74,17,calfresh,California,2019,3,Santa Barbara,113.9,431555,1707,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1828,0,0
75,17,calfresh,California,2019,3,Tulare,93.2,451108,2189,79,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1809,0,0
76,17,calfresh,California,2019,3,Ventura,378.5,835790,2730,174,0,2019-03-01 00:00:00,2019-02-01 00:00:00,2436,246,0
77,25,calfresh,California,2019,3,Inyo,1.8,18439,59,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,38,0,0
78,25,calfresh,California,2019,3,Kern,105.1,857730,5118,542,0,2019-03-01 00:00:00,2019-02-01 00:00:00,4841,175,0
79,25,calfresh,California,2019,3,Orange,3255.4,3086331,7611,543,0,2019-03-01 00:00:00,2019-02-01 00:00:00,6872,350,0
80,25,calfresh,California,2019,3,San Diego,703.4,3183143,10698,383,0,2019-03-01 00:00:00,2019-02-01 00:00:00,10538,268,0
81,25,calfresh,California,2019,3,Santa Barbara,113.9,431555,1707,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1828,0,0
82,25,calfresh,California,2019,3,Tulare,93.2,451108,2189,79,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1809,0,0
83,25,calfresh,California,2019,3,Ventura,378.5,835790,2730,174,0,2019-03-01 00:00:00,2019-02-01 00:00:00,2436,246,0
84,26,calfresh,California,2019,3,Inyo,1.8,18439,59,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,38,0,0
85,26,calfresh,California,2019,3,Kern,105.1,857730,5118,542,0,2019-03-01 00:00:00,2019-02-01 00:00:00,4841,175,0
86,26,calfresh,California,2019,3,Orange,3255.4,3086331,7611,543,0,2019-03-01 00:00:00,2019-02-01 00:00:00,6872,350,0
87,26,calfresh,California,2019,3,San Diego,703.4,3183143,10698,383,0,2019-03-01 00:00:00,2019-02-01 00:00:00,10538,268,0
88,26,calfresh,California,2019,3,Santa Barbara,113.9,431555,1707,0,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1828,0,0
89,26,calfresh,California,2019,3,Tulare,93.2,451108,2189,79,0,2019-03-01 00:00:00,2019-02-01 00:00:00,1809,0,0
90,26,calfresh,California,2019,3,Ventura,378.5,835790,2730,174,0,2019-03-01 00:00:00,2019-02-01 00:00:00,2436,246,0
91,23,calfresh,California,2019,4,Inyo,1.8,18439,60,0,0,2019-04-01 00:00:00,2019-03-01 00:00:00,59,0,0
92,23,calfresh,California,2019,4,Kern,105.1,857730,5375,0,0,2019-04-01 00:00:00,2019-03-01 00:00:00,5118,542,0
93,23,calfresh,California,2019,4,Orange,3255.4,3086331,8204,834,0,2019-04-01 00:00:00,2019-03-01 00:00:00,7611,543,0
94,23,calfresh,California,2019,4,San Diego,703.4,3183143,11579,258,0,2019-04-01 00:00:00,2019-03-01 00:00:00,10698,383,0
95,23,calfresh,California,2019,4,Santa Barbara,113.9,431555,1911,0,0,2019-04-01 00:00:00,2019-03-01 00:00:00,1707,0,0
96,23,calfresh,California,2019,4,Tulare,93.2,451108,2141,0,0,2019-04-01 00:00:00,2019-03-01 00:00:00,2189,79,0
97,23,calfresh,California,2019,4,Ventura,378.5,835790,2685,51,0,2019-04-01 00:00:00,2019-03-01 00:00:00,2730,174,0
98,20,calfresh,California,2019,4,Inyo,1.8,18439,60,0,0,2019-04-01 00:00:00,2019-03-01 00:00:00,59,0,0
99,20,calfresh,California,2019,4,Kern,105.1,857730,5375,0,0,2019-04-01 00:00:00,2019-03-01 00:00:00,5118,542,0

In [18]:
#df1.to_excel('databaseForFunction.xlsx')

In [308]:
len(df1)

236340

In [309]:
# find last_snap, last_workder, last_disater by the key [last_date_time, County and State]

test = df1.copy()[0:10000]

In [310]:
test.head(20)

,Search,Search term,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster
0,24,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
1,24,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
2,24,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
3,24,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
4,24,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0
5,24,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0
6,24,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0
7,34,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
8,34,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
9,34,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
10,34,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
11,34,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0
12,34,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0
13,34,calfresh,California,2019,1,Ventura,378.5,835790,2956,0,0
14,26,calfresh,California,2019,1,Inyo,1.8,18439,84,0,0
15,26,calfresh,California,2019,1,Kern,105.1,857730,6163,134,0
16,26,calfresh,California,2019,1,Orange,3255.4,3086331,8637,200,0
17,26,calfresh,California,2019,1,San Diego,703.4,3183143,12905,140,0
18,26,calfresh,California,2019,1,Santa Barbara,113.9,431555,2509,0,0
19,26,calfresh,California,2019,1,Tulare,93.2,451108,2231,63,0

#### Rename the col for convenience

In [311]:
test.rename(columns={"Search term": "Searchterm"}, inplace = True)

#### Debug: use mean to instead 4 different search number for each word

In [312]:
test = test.groupby(['Searchterm','State','Year','Month','County','Population Density','Population','SNAP_Applications','Number of Workers','# of disaster'])['Search'].mean().reset_index()

In [313]:
test.head(10)

,Searchterm,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster,Search
0,calfresh,California,2019,1,Alpine,1.6,1202,4,0,0,37.0
1,calfresh,California,2019,1,Amador,61.3,37159,154,0,0,37.0
2,calfresh,California,2019,1,Butte,132.1,221578,2043,1373,0,37.0
3,calfresh,California,2019,1,Calaveras,43.3,44921,221,0,0,37.0
4,calfresh,California,2019,1,Colusa,18.5,21424,88,0,0,37.0
5,calfresh,California,2019,1,Del Norte,22.8,28066,176,0,0,37.0
6,calfresh,California,2019,1,El Dorado,101.6,181465,641,0,0,37.0
7,calfresh,California,2019,1,Fresno,157.8,948844,5541,0,0,37.0
8,calfresh,California,2019,1,Glenn,21.1,28019,158,0,0,37.0
9,calfresh,California,2019,1,Humboldt,33.3,134876,1328,0,0,37.0

#### Create empty cols

In [111]:
# # create col for last month 
# test['last_snap'] = None
# test['last_worker'] = None
# test['last_disaster'] = None

In [314]:
# create col for each search for last month

search = set(test['Searchterm'].unique())
search

{'calfresh',
 'food bank',
 'food pantry',
 'food stamps',
 'supplemental nutrition assistance program'}

In [315]:
for word in search:
    test[word] = None
    
test.head(5)

,Searchterm,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster,Search,food stamps,supplemental nutrition assistance program,food bank,food pantry,calfresh
0,calfresh,California,2019,1,Alpine,1.6,1202,4,0,0,37.0,None,None,None,None,None
1,calfresh,California,2019,1,Amador,61.3,37159,154,0,0,37.0,None,None,None,None,None
2,calfresh,California,2019,1,Butte,132.1,221578,2043,1373,0,37.0,None,None,None,None,None
3,calfresh,California,2019,1,Calaveras,43.3,44921,221,0,0,37.0,None,None,None,None,None
4,calfresh,California,2019,1,Colusa,18.5,21424,88,0,0,37.0,None,None,None,None,None

In [316]:
# word : idx in database

lookup = {
    'calfresh':-1,
    'food pantry':-2,
    'food bank':-3,
    'supplemental nutrition assistance program':-4,
    'food stamps':-5
}

In [317]:
for i in range(len(test)):
    term = test.iloc[i,0]
    value = test.iloc[i,10]
    idx = lookup[term]
    test.iloc[i, idx] = value

In [318]:
test.tail()

,Searchterm,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster,Search,food stamps,supplemental nutrition assistance program,food bank,food pantry,calfresh
2309,supplemental nutrition assistance program,California,2021,12,Orange,3255.4,3086331,11251,527,0,40.75,None,40.75,None,None,None
2310,supplemental nutrition assistance program,California,2021,12,San Diego,703.4,3183143,16708,157,0,40.75,None,40.75,None,None,None
2311,supplemental nutrition assistance program,California,2021,12,Santa Barbara,113.9,431555,2408,0,0,40.75,None,40.75,None,None,None
2312,supplemental nutrition assistance program,California,2021,12,Tulare,93.2,451108,3725,0,0,40.75,None,40.75,None,None,None
2313,supplemental nutrition assistance program,California,2021,12,Ventura,378.5,835790,2910,58,0,40.75,None,40.75,None,None,None

In [319]:
state = ['California', 'Texas']
county = test.County.unique()
year = test.Year.unique()
month = test.Month.unique()

In [325]:
county

array(['Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa', 'Del Norte',
       'El Dorado', 'Fresno', 'Glenn', 'Humboldt', 'Inyo', 'Kern',
       'Kings', 'Lake', 'Lassen', 'Madera', 'Mariposa', 'Merced', 'Modoc',
       'Mono', 'Orange', 'Placer', 'Plumas', 'Sacramento', 'San Diego',
       'San Joaquin', 'Santa Barbara', 'Shasta', 'Sierra', 'Siskiyou',
       'Stanislaus', 'Sutter', 'Tehama', 'Tulare', 'Tuolumne', 'Ventura',
       'Yolo', 'Yuba'], dtype=object)

In [320]:
col = test.columns

In [333]:
new = pd.DataFrame(columns=col)

In [334]:
new

Empty DataFrame
Columns: [Searchterm, State, Year, Month, County, Population Density, Population, SNAP_Applications, Number of Workers, # of disaster, Search, food stamps, supplemental nutrition assistance program, food bank, food pantry, calfresh]
Index: []

In [335]:
count = 0

In [336]:
month

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [337]:


for s in state:
    for c in county:
        for y in year:
            for m in month:
                cur_table = test.loc[(test.State == s) & (test.County == c) & (test.Year == y) & (test.Month == m)]
                
                while count <= 10:
                    if len(cur_table) == 5:
                        count += 1
                        cur_table
                        cur_table = cur_table.fillna(method = 'backfill')
                        cur_row = cur_table[:1]
                        new = pd.concat([new,cur_row]).reset_index(drop=True)

KeyboardInterrupt:

In [ ]:
new

In [157]:
test[:5]

,Searchterm,State,Year,Month,County,Population Density,Population,SNAP_Applications,Number of Workers,# of disaster,Search,food stamps,supplemental nutrition assistance program,food bank,food pantry,calfresh
0,calfresh,California,2019,1,Alpine,1.6,1202,4,0,0,37.0,0,0,0,0,0
1,calfresh,California,2019,1,Amador,61.3,37159,154,0,0,37.0,0,0,0,0,0
2,calfresh,California,2019,1,Butte,132.1,221578,2043,1373,0,37.0,0,0,0,0,0
3,calfresh,California,2019,1,Calaveras,43.3,44921,221,0,0,37.0,0,0,0,0,0
4,calfresh,California,2019,1,Colusa,18.5,21424,88,0,0,37.0,0,0,0,0,0

In [14]:

for i in range(len(test)):
    state = test.iloc[i, 2]
    county = test.iloc[i, 5]
    last_date_time = test.last_date_time[i]
    
    filtet_table = test.loc[(test.date_time == last_date_time) & (test.State == state) & (test.County == county)]
    
    
    if len(filtet_table) != 0:
        test.iloc[i, -1] = filtet_table['# of disaster'].values[0]
        test.iloc[i, -2] = filtet_table['Number of Workers'].values[0]
        test.iloc[i, -3] = filtet_table.SNAP_Applications.values[0]